org.gradle.jvmargs=-Xmx4G --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
loader_version=0.19.5
loom_version=1.17.20
minecraft_version=26.2

fabric_api_version=0.160.0+26.2

mod_version=0.5.1
maven_group=cheesecake
archives_base_name=cheesecake
java_version=25
nether_pathfinder_version=1.6
